services:
    _defaults:
        public: true
        bind:
          $elasticConfig: '%elastic%'

    App\Tests\Infrastructure\Share\Event\EventCollectorListener:
      public: true
      autowire: true
      autoconfigure: true

    App\Infrastructure\Share\Event\Query\EventElasticRepository:
      public: true

    Messenger\Bus\CommandBus:
      public: true
      arguments:
        - '@messenger.bus.command'